---
# tasks file for get-envs

#task utilizando o service manager 
- name: lookup secretsmanager secret in the current region
  set_fact: 
    secret_value: "{{ lookup('aws_ssm', 'teste-2') | split(',') }}"
    secret_value2: "{{lookup('aws_ssm', 'teste')}}"

# task utilizando o secrets manager 
- name: lookup secretsmanager secret in the current region
  set_fact: 
    secret_value: "{{ lookup('amazon.aws.aws_secret', 'DB_CONNECTION_FM_GEO') }}"


- name: template
  template:
    src: "./templates/.env.j2"
    dest: "/home/ubuntu/.env"
    mode: 0755
    force: true
    owner: www-data
    group: www-data